"""user settings

Revision ID: 502a7e5c17ab
Revises: b1ebe6dc222c
Create Date: 2021-02-23 23:08:21.465597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502a7e5c17ab'
down_revision = 'b1ebe6dc222c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notifications_general_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_advance_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_advance_days_until_expiration', sa.Integer(), nullable=True),
    sa.Column('notifications_periodical_frequency', sa.Integer(), nullable=True),
    sa.Column('notifications_weekly_enabled', sa.Boolean(), nullable=True),
    sa.Column('notifications_weekly_day', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
