"""modify user entity

Revision ID: 5f4c92631cd8
Revises: ad78211113eb
Create Date: 2020-11-14 22:21:28.673554

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5f4c92631cd8'
down_revision = 'ad78211113eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), server_default="No Name", nullable=False))
    op.add_column('users', sa.Column('language', sa.String(), server_default="en_US", nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                                     nullable=True))
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'language')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
