"""enables notifications frequency

Revision ID: 6139bb48f1c8
Revises: 502a7e5c17ab
Create Date: 2021-03-24 21:41:10.802214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6139bb48f1c8'
down_revision = '502a7e5c17ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notifications_periodical_frequency_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'notifications_periodical_frequency_enabled')
    # ### end Alembic commands ###
