"""Add automatic_bought_date column

Revision ID: 9106395c2f3d
Revises: e3aac87cd050
Create Date: 2021-05-10 19:37:41.209368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9106395c2f3d'
down_revision = 'e3aac87cd050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('automatic_bought_date', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'automatic_bought_date')
    # ### end Alembic commands ###
