"""add shopping list to product relation

Revision ID: b1ebe6dc222c
Revises: 4d7180049274
Create Date: 2020-11-15 00:25:06.851149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ebe6dc222c'
down_revision = '4d7180049274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list_to_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_to_product_id'), 'shopping_list_to_product', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_to_product_id'), table_name='shopping_list_to_product')
    op.drop_table('shopping_list_to_product')
    # ### end Alembic commands ###
