"""Create last_day_notify column

Revision ID: e3aac87cd050
Revises: 0b4025914a12
Create Date: 2021-05-10 16:08:20.448006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aac87cd050'
down_revision = '0b4025914a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('last_notify_day_frequency', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'last_notify_day_frequency')
    # ### end Alembic commands ###
