from .start import command_start_handler
from .my_fridge import my_fridge_handler
from .my_fridge import my_fridge_handler_st
from .shopping_list import shopping_list_handler_st
from .shopping_list import shopping_list_handler
from .find_recipe import find_recipe_handler_st
from .find_recipe import find_recipe_handler
from .help import help_handler_st
from .help import help_handler
from .Settings import settings_handler_st
from .Settings import settings_handler
